// Mock data for development - Real Colombo bus routes
import { BusRoute, BusStop, RouteStop } from './types';

export const mockStops: BusStop[] = [
    // Central Colombo
    {
        id: 'stop-1',
        name: 'Fort Railway Station',
        name_si: 'කොළඹ කොටුව දුම්රිය ස්ථානය',
        name_ta: 'கோட்டை ரயில் நிலையம்',
        latitude: 6.9344,
        longitude: 79.8428,
        landmark: 'Main railway station, Central Bus Stand nearby',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-2',
        name: 'Pettah Bus Stand',
        name_si: 'පිටකොටුව බස් නැවතුම',
        name_ta: 'பேட்டா பஸ் நிலையம்',
        latitude: 6.9366,
        longitude: 79.8486,
        landmark: 'Central Pettah market area',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-3',
        name: 'Maradana',
        name_si: 'මරදාන',
        name_ta: 'மருதானை',
        latitude: 6.9289,
        longitude: 79.8654,
        landmark: 'Near Maradana Railway Station',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-4',
        name: 'Borella Junction',
        name_si: 'බොරැල්ල හන්දිය',
        name_ta: 'பொரெல்ல சந்தி',
        latitude: 6.9147,
        longitude: 79.8773,
        landmark: 'Major junction, near Cancer Hospital',
        created_at: new Date().toISOString(),
    },
    // Kollupitiya / Galle Road
    {
        id: 'stop-5',
        name: 'Kollupitiya',
        name_si: 'කොල්ලුපිටිය',
        name_ta: 'கொள்ளுப்பிட்டி',
        latitude: 6.9107,
        longitude: 79.8499,
        landmark: 'Liberty Plaza, Galle Road',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-6',
        name: 'Bambalapitiya',
        name_si: 'බම්බලපිටිය',
        name_ta: 'பம்பலப்பிட்டி',
        latitude: 6.8933,
        longitude: 79.8559,
        landmark: 'Savoy Cinema, Galle Road',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-7',
        name: 'Wellawatte',
        name_si: 'වැල්ලවත්ත',
        name_ta: 'வெள்ளவத்தை',
        latitude: 6.8744,
        longitude: 79.8611,
        landmark: 'Wellawatte Junction',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-8',
        name: 'Dehiwala',
        name_si: 'දෙහිවල',
        name_ta: 'தெஹிவளை',
        latitude: 6.8519,
        longitude: 79.8654,
        landmark: 'Near Dehiwala Zoo',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-9',
        name: 'Mount Lavinia',
        name_si: 'ගල්කිස්ස',
        name_ta: 'கல்கிசை',
        latitude: 6.8283,
        longitude: 79.8659,
        landmark: 'Mount Lavinia Beach, Hotel',
        created_at: new Date().toISOString(),
    },
    // Eastern Route
    {
        id: 'stop-10',
        name: 'Nugegoda',
        name_si: 'නුගේගොඩ',
        name_ta: 'நுகேகொட',
        latitude: 6.8728,
        longitude: 79.8899,
        landmark: 'Super Market Complex, High Level Road',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-11',
        name: 'Maharagama',
        name_si: 'මහරගම',
        name_ta: 'மஹரகம',
        latitude: 6.8467,
        longitude: 79.9269,
        landmark: 'Maharagama Town',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-12',
        name: 'Kottawa',
        name_si: 'කොට්ටාව',
        name_ta: 'கொட்டாவ',
        latitude: 6.8417,
        longitude: 79.9647,
        landmark: 'Kottawa Junction',
        created_at: new Date().toISOString(),
    },
    // Rajagiriya / Battaramulla
    {
        id: 'stop-13',
        name: 'Rajagiriya',
        name_si: 'රාජගිරිය',
        name_ta: 'ராஜகிரிய',
        latitude: 6.9066,
        longitude: 79.8961,
        landmark: 'Parliament Road',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-14',
        name: 'Battaramulla',
        name_si: 'බත්තරමුල්ල',
        name_ta: 'பத்தரமுல்ல',
        latitude: 6.8989,
        longitude: 79.9178,
        landmark: 'Near Parliament',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-15',
        name: 'Malabe',
        name_si: 'මාලබේ',
        name_ta: 'மாலபே',
        latitude: 6.9022,
        longitude: 79.9558,
        landmark: 'SLIIT, NSBM University',
        created_at: new Date().toISOString(),
    },
    // South
    {
        id: 'stop-16',
        name: 'Moratuwa',
        name_si: 'මොරටුව',
        name_ta: 'மொரட்டுவ',
        latitude: 6.7733,
        longitude: 79.8819,
        landmark: 'University of Moratuwa',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-17',
        name: 'Panadura',
        name_si: 'පානදුර',
        name_ta: 'பாணந்துறை',
        latitude: 6.7133,
        longitude: 79.9044,
        landmark: 'Panadura Town',
        created_at: new Date().toISOString(),
    },
    // North
    {
        id: 'stop-18',
        name: 'Peliyagoda',
        name_si: 'පැලියගොඩ',
        name_ta: 'பெலியகொட',
        latitude: 6.9611,
        longitude: 79.8833,
        landmark: 'Near Manning Market',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-19',
        name: 'Kadawatha',
        name_si: 'කඩවත',
        name_ta: 'கடவத்த',
        latitude: 7.0022,
        longitude: 79.9431,
        landmark: 'Kadawatha Town',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-20',
        name: 'Kiribathgoda',
        name_si: 'කිරිබත්ගොඩ',
        name_ta: 'கிரிபத்கொட',
        latitude: 6.9783,
        longitude: 79.9289,
        landmark: 'Kiribathgoda Junction',
        created_at: new Date().toISOString(),
    },
    // NEW STOPS - Thalawathugoda and surrounding areas
    {
        id: 'stop-21',
        name: 'Thalawathugoda',
        name_si: 'තලවතුගොඩ',
        name_ta: 'தலவத்துகொட',
        latitude: 6.8747,
        longitude: 79.9123,
        landmark: 'Thalawathugoda Junction, near Supermarkets',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-22',
        name: 'Nawala',
        name_si: 'නාවල',
        name_ta: 'நாவல',
        latitude: 6.8933,
        longitude: 79.8889,
        landmark: 'Nawala Junction, near OUSL',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-23',
        name: 'Narahenpita',
        name_si: 'නාරාහේන්පිට',
        name_ta: 'நாரஹேன்பிட்ட',
        latitude: 6.9006,
        longitude: 79.8672,
        landmark: 'Near Narahenpita Junction',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-24',
        name: 'Kotte',
        name_si: 'කෝට්ටේ',
        name_ta: 'கோட்டே',
        latitude: 6.8914,
        longitude: 79.9039,
        landmark: 'Sri Jayawardenepura Kotte',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-25',
        name: 'Pitakotte',
        name_si: 'පිටකෝට්ටේ',
        name_ta: 'பிட்டகோட்டே',
        latitude: 6.8883,
        longitude: 79.8961,
        landmark: 'Pitakotte Junction',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-26',
        name: 'Ethul Kotte',
        name_si: 'ඇතුල් කෝට්ටේ',
        name_ta: 'எத்துல்கோட்டே',
        latitude: 6.8856,
        longitude: 79.9069,
        landmark: 'Near Kotte Raja Maha Viharaya',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-27',
        name: 'Hokandara',
        name_si: 'හොකන්දර',
        name_ta: 'ஹொகந்தர',
        latitude: 6.8628,
        longitude: 79.9336,
        landmark: 'Hokandara Junction',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-28',
        name: 'Athurugiriya',
        name_si: 'අතුරුගිරිය',
        name_ta: 'அத்துருகிரிய',
        latitude: 6.8694,
        longitude: 79.9503,
        landmark: 'Athurugiriya Town',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-29',
        name: 'Mirihana',
        name_si: 'මිරිහාන',
        name_ta: 'மிரிஹான',
        latitude: 6.8722,
        longitude: 79.9042,
        landmark: 'Mirihana Junction',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-30',
        name: 'Wijerama',
        name_si: 'විජේරාම',
        name_ta: 'விஜேராம',
        latitude: 6.8772,
        longitude: 79.8856,
        landmark: 'Wijerama Junction',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-31',
        name: 'Kelaniya',
        name_si: 'කැලණිය',
        name_ta: 'கெலனியா',
        latitude: 6.9553,
        longitude: 79.9147,
        landmark: 'Kelaniya Temple',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-32',
        name: 'Wattala',
        name_si: 'වත්තල',
        name_ta: 'வத்தளை',
        latitude: 6.9878,
        longitude: 79.8917,
        landmark: 'Wattala Town',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-33',
        name: 'Ja-Ela',
        name_si: 'ජා ඇල',
        name_ta: 'ஜா-எல',
        latitude: 7.0744,
        longitude: 79.8917,
        landmark: 'Ja-Ela Town',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-34',
        name: 'Negombo',
        name_si: 'මීගමුව',
        name_ta: 'நீர்கொழும்பு',
        latitude: 7.2111,
        longitude: 79.8386,
        landmark: 'Negombo Bus Stand',
        created_at: new Date().toISOString(),
    },
    {
        id: 'stop-35',
        name: 'Katunayake',
        name_si: 'කටුනායක',
        name_ta: 'கட்டுநாயக்க',
        latitude: 7.1697,
        longitude: 79.8886,
        landmark: 'Near Airport',
        created_at: new Date().toISOString(),
    },
];

// Create route stops helper
const createRouteStops = (routeId: string, stopIds: string[], times: number[]): RouteStop[] => {
    return stopIds.map((stopId, index) => ({
        id: `rs-${routeId}-${index}`,
        route_id: routeId,
        stop_id: stopId,
        stop_order: index + 1,
        estimated_time_from_start_mins: times[index],
    }));
};

export const mockRoutes: BusRoute[] = [
    // Route 138 - Pettah to Maharagama (via Galle Road)
    {
        id: 'route-138',
        route_number: '138',
        route_name: 'Pettah - Maharagama',
        description: 'Popular route via Galle Road, connecting Fort to Maharagama through coastal suburbs',
        fare_estimate: 60,
        estimated_duration_mins: 55,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-138',
            ['stop-2', 'stop-1', 'stop-5', 'stop-6', 'stop-7', 'stop-8', 'stop-10', 'stop-11'],
            [0, 5, 15, 25, 32, 40, 48, 55]
        ),
    },
    // Route 154 - Pettah to Kottawa
    {
        id: 'route-154',
        route_number: '154',
        route_name: 'Pettah - Kottawa',
        description: 'Direct route to Kottawa via Borella and High Level Road',
        fare_estimate: 75,
        estimated_duration_mins: 65,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-154',
            ['stop-2', 'stop-3', 'stop-4', 'stop-10', 'stop-11', 'stop-12'],
            [0, 8, 18, 35, 50, 65]
        ),
    },
    // Route 100 - Pettah to Panadura
    {
        id: 'route-100',
        route_number: '100',
        route_name: 'Pettah - Panadura',
        description: 'Coastal route via Galle Road all the way to Panadura',
        fare_estimate: 90,
        estimated_duration_mins: 80,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-100',
            ['stop-2', 'stop-1', 'stop-5', 'stop-6', 'stop-7', 'stop-8', 'stop-9', 'stop-16', 'stop-17'],
            [0, 5, 15, 25, 32, 40, 50, 65, 80]
        ),
    },
    // Route 255 - Pettah to Malabe
    {
        id: 'route-255',
        route_number: '255',
        route_name: 'Pettah - Malabe',
        description: 'Eastern route via Parliament Road to Malabe tech hub',
        fare_estimate: 70,
        estimated_duration_mins: 60,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-255',
            ['stop-2', 'stop-3', 'stop-4', 'stop-13', 'stop-14', 'stop-15'],
            [0, 8, 18, 32, 45, 60]
        ),
    },
    // Route 120 - Pettah to Kadawatha
    {
        id: 'route-120',
        route_number: '120',
        route_name: 'Pettah - Kadawatha',
        description: 'Northern route to Kadawatha via Peliyagoda',
        fare_estimate: 55,
        estimated_duration_mins: 45,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-120',
            ['stop-2', 'stop-18', 'stop-20', 'stop-19'],
            [0, 12, 28, 45]
        ),
    },
    // Route 176 - Battaramulla to Kollupitiya
    {
        id: 'route-176',
        route_number: '176',
        route_name: 'Battaramulla - Kollupitiya',
        description: 'Cross-city route connecting Parliament area to Galle Road',
        fare_estimate: 50,
        estimated_duration_mins: 40,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-176',
            ['stop-14', 'stop-13', 'stop-4', 'stop-3', 'stop-5'],
            [0, 10, 22, 32, 40]
        ),
    },
    // Route 158 - Nugegoda to Fort
    {
        id: 'route-158',
        route_number: '158',
        route_name: 'Nugegoda - Fort',
        description: 'Direct route from Nugegoda to Fort via Baseline Road',
        fare_estimate: 45,
        estimated_duration_mins: 35,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-158',
            ['stop-10', 'stop-4', 'stop-3', 'stop-1'],
            [0, 12, 22, 35]
        ),
    },
    // Route 171 - Kollupitiya to Thalawathugoda
    {
        id: 'route-171',
        route_number: '171',
        route_name: 'Kollupitiya - Thalawathugoda',
        description: 'Route from Galle Road to Thalawathugoda via Nawala',
        fare_estimate: 55,
        estimated_duration_mins: 45,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-171',
            ['stop-5', 'stop-23', 'stop-22', 'stop-25', 'stop-24', 'stop-29', 'stop-21'],
            [0, 10, 18, 25, 30, 38, 45]
        ),
    },
    // Route 135 - Borella to Athurugiriya
    {
        id: 'route-135',
        route_number: '135',
        route_name: 'Borella - Athurugiriya',
        description: 'Eastern route via Thalawathugoda to Athurugiriya',
        fare_estimate: 65,
        estimated_duration_mins: 55,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-135',
            ['stop-4', 'stop-10', 'stop-30', 'stop-21', 'stop-27', 'stop-28'],
            [0, 12, 22, 32, 45, 55]
        ),
    },
    // Route 177 - Pettah to Negombo
    {
        id: 'route-177',
        route_number: '177',
        route_name: 'Pettah - Negombo',
        description: 'Long route to Negombo via Wattala',
        fare_estimate: 120,
        estimated_duration_mins: 90,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-177',
            ['stop-2', 'stop-18', 'stop-32', 'stop-33', 'stop-35', 'stop-34'],
            [0, 15, 30, 50, 70, 90]
        ),
    },
    // Route 178 - Kollupitiya to Kotte
    {
        id: 'route-178',
        route_number: '178',
        route_name: 'Kollupitiya - Kotte',
        description: 'Route connecting Galle Road to Sri Jayawardenepura Kotte',
        fare_estimate: 40,
        estimated_duration_mins: 35,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-178',
            ['stop-5', 'stop-23', 'stop-22', 'stop-25', 'stop-26', 'stop-24'],
            [0, 8, 15, 22, 28, 35]
        ),
    },
    // Route 103 - Pettah to Kelaniya
    {
        id: 'route-103',
        route_number: '103',
        route_name: 'Pettah - Kelaniya',
        description: 'Route to Kelaniya Temple',
        fare_estimate: 35,
        estimated_duration_mins: 30,
        status: 'verified',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        stops: createRouteStops('route-103',
            ['stop-2', 'stop-18', 'stop-31'],
            [0, 12, 30]
        ),
    },
];

// Populate stop data in routes
mockRoutes.forEach(route => {
    if (route.stops) {
        route.stops.forEach(routeStop => {
            routeStop.stop = mockStops.find(s => s.id === routeStop.stop_id);
        });
    }
});

